// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: asr.proto

package asrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AudioEncoding enumerates the accepted raw audio encodings.
type AudioEncoding int32

const (
	AudioEncoding_AUDIO_ENCODING_UNSPECIFIED AudioEncoding = 0
	AudioEncoding_AUDIO_ENCODING_LINEAR16    AudioEncoding = 1 // 16-bit signed little-endian PCM
	AudioEncoding_AUDIO_ENCODING_FLAC        AudioEncoding = 2
	AudioEncoding_AUDIO_ENCODING_OGG_OPUS    AudioEncoding = 3
	AudioEncoding_AUDIO_ENCODING_MULAW       AudioEncoding = 4
)

// Enum value maps for AudioEncoding.
var (
	AudioEncoding_name = map[int32]string{
		0: "AUDIO_ENCODING_UNSPECIFIED",
		1: "AUDIO_ENCODING_LINEAR16",
		2: "AUDIO_ENCODING_FLAC",
		3: "AUDIO_ENCODING_OGG_OPUS",
		4: "AUDIO_ENCODING_MULAW",
	}
	AudioEncoding_value = map[string]int32{
		"AUDIO_ENCODING_UNSPECIFIED": 0,
		"AUDIO_ENCODING_LINEAR16":    1,
		"AUDIO_ENCODING_FLAC":        2,
		"AUDIO_ENCODING_OGG_OPUS":    3,
		"AUDIO_ENCODING_MULAW":       4,
	}
)

func (x AudioEncoding) Enum() *AudioEncoding {
	p := new(AudioEncoding)
	*p = x
	return p
}

func (x AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_asr_proto_enumTypes[0].Descriptor()
}

func (AudioEncoding) Type() protoreflect.EnumType {
	return &file_asr_proto_enumTypes[0]
}

func (x AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioEncoding.Descriptor instead.
func (AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

// RecognitionConfig is sent once, before any audio, to configure the recognizer.
type RecognitionConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Encoding       AudioEncoding          `protobuf:"varint,1,opt,name=encoding,proto3,enum=asr.v1.AudioEncoding" json:"encoding,omitempty"`
	SampleRateHz   int32                  `protobuf:"varint,2,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`     // e.g. 16000
	LanguageCode   string                 `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`        // BCP-47, e.g. "en-US"
	InterimResults bool                   `protobuf:"varint,4,opt,name=interim_results,json=interimResults,proto3" json:"interim_results,omitempty"` // request interim transcripts (default true)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecognitionConfig) Reset() {
	*x = RecognitionConfig{}
	mi := &file_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionConfig) ProtoMessage() {}

func (x *RecognitionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionConfig.ProtoReflect.Descriptor instead.
func (*RecognitionConfig) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{0}
}

func (x *RecognitionConfig) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_AUDIO_ENCODING_UNSPECIFIED
}

func (x *RecognitionConfig) GetSampleRateHz() int32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *RecognitionConfig) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *RecognitionConfig) GetInterimResults() bool {
	if x != nil {
		return x.InterimResults
	}
	return false
}

// StreamingRecognizeRequest is a oneof: the first message MUST be `config`,
// every subsequent message MUST be `audio_content`.
type StreamingRecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StreamingRequest:
	//
	//	*StreamingRecognizeRequest_Config
	//	*StreamingRecognizeRequest_AudioContent
	StreamingRequest isStreamingRecognizeRequest_StreamingRequest `protobuf_oneof:"streaming_request"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamingRecognizeRequest) Reset() {
	*x = StreamingRecognizeRequest{}
	mi := &file_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeRequest) ProtoMessage() {}

func (x *StreamingRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeRequest.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingRecognizeRequest) GetStreamingRequest() isStreamingRecognizeRequest_StreamingRequest {
	if x != nil {
		return x.StreamingRequest
	}
	return nil
}

func (x *StreamingRecognizeRequest) GetConfig() *RecognitionConfig {
	if x != nil {
		if x, ok := x.StreamingRequest.(*StreamingRecognizeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *StreamingRecognizeRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.StreamingRequest.(*StreamingRecognizeRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

type isStreamingRecognizeRequest_StreamingRequest interface {
	isStreamingRecognizeRequest_StreamingRequest()
}

type StreamingRecognizeRequest_Config struct {
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type StreamingRecognizeRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"` // raw audio bytes in the configured encoding
}

func (*StreamingRecognizeRequest_Config) isStreamingRecognizeRequest_StreamingRequest() {}

func (*StreamingRecognizeRequest_AudioContent) isStreamingRecognizeRequest_StreamingRequest() {}

// StreamingRecognizeResponse carries a transcript result or a stream-level error.
type StreamingRecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*StreamingResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         *StreamError           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // set when the server aborts the stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeResponse) Reset() {
	*x = StreamingRecognizeResponse{}
	mi := &file_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeResponse) ProtoMessage() {}

func (x *StreamingRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeResponse.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{2}
}

func (x *StreamingRecognizeResponse) GetResults() []*StreamingResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *StreamingRecognizeResponse) GetError() *StreamError {
	if x != nil {
		return x.Error
	}
	return nil
}

// StreamingResult is one recognition hypothesis.
type StreamingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // final (true) vs. interim (false) — FR-005
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`         // 0..1, optional (final results)
	Stability     float32                `protobuf:"fixed32,4,opt,name=stability,proto3" json:"stability,omitempty"`           // 0..1, optional (interim results)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingResult) Reset() {
	*x = StreamingResult{}
	mi := &file_asr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingResult) ProtoMessage() {}

func (x *StreamingResult) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingResult.ProtoReflect.Descriptor instead.
func (*StreamingResult) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{3}
}

func (x *StreamingResult) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *StreamingResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamingResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *StreamingResult) GetStability() float32 {
	if x != nil {
		return x.Stability
	}
	return 0
}

// StreamError is a structured, server-originated stream failure.
type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // e.g. "invalid_config", "internal", "unsupported_format"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_asr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_asr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_asr_proto_rawDescGZIP(), []int{4}
}

func (x *StreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_asr_proto protoreflect.FileDescriptor

const file_asr_proto_rawDesc = "" +
	"\n" +
	"\tasr.proto\x12\x06asr.v1\"\xba\x01\n" +
	"\x11RecognitionConfig\x121\n" +
	"\bencoding\x18\x01 \x01(\x0e2\x15.asr.v1.AudioEncodingR\bencoding\x12$\n" +
	"\x0esample_rate_hz\x18\x02 \x01(\x05R\fsampleRateHz\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x12'\n" +
	"\x0finterim_results\x18\x04 \x01(\bR\x0einterimResults\"\x8c\x01\n" +
	"\x19StreamingRecognizeRequest\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x19.asr.v1.RecognitionConfigH\x00R\x06config\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContentB\x13\n" +
	"\x11streaming_request\"z\n" +
	"\x1aStreamingRecognizeResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.asr.v1.StreamingResultR\aresults\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x13.asr.v1.StreamErrorR\x05error\"\x8a\x01\n" +
	"\x0fStreamingResult\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\tstability\x18\x04 \x01(\x02R\tstability\";\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x9c\x01\n" +
	"\rAudioEncoding\x12\x1e\n" +
	"\x1aAUDIO_ENCODING_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AUDIO_ENCODING_LINEAR16\x10\x01\x12\x17\n" +
	"\x13AUDIO_ENCODING_FLAC\x10\x02\x12\x1b\n" +
	"\x17AUDIO_ENCODING_OGG_OPUS\x10\x03\x12\x18\n" +
	"\x14AUDIO_ENCODING_MULAW\x10\x042m\n" +
	"\n" +
	"ASRService\x12_\n" +
	"\x12StreamingRecognize\x12!.asr.v1.StreamingRecognizeRequest\x1a\".asr.v1.StreamingRecognizeResponse(\x010\x01B:Z8github.com/harshithgowda/asr/internal/genproto/asr;asrv1b\x06proto3"

var (
	file_asr_proto_rawDescOnce sync.Once
	file_asr_proto_rawDescData []byte
)

func file_asr_proto_rawDescGZIP() []byte {
	file_asr_proto_rawDescOnce.Do(func() {
		file_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)))
	})
	return file_asr_proto_rawDescData
}

var file_asr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_asr_proto_goTypes = []any{
	(AudioEncoding)(0),                 // 0: asr.v1.AudioEncoding
	(*RecognitionConfig)(nil),          // 1: asr.v1.RecognitionConfig
	(*StreamingRecognizeRequest)(nil),  // 2: asr.v1.StreamingRecognizeRequest
	(*StreamingRecognizeResponse)(nil), // 3: asr.v1.StreamingRecognizeResponse
	(*StreamingResult)(nil),            // 4: asr.v1.StreamingResult
	(*StreamError)(nil),                // 5: asr.v1.StreamError
}
var file_asr_proto_depIdxs = []int32{
	0, // 0: asr.v1.RecognitionConfig.encoding:type_name -> asr.v1.AudioEncoding
	1, // 1: asr.v1.StreamingRecognizeRequest.config:type_name -> asr.v1.RecognitionConfig
	4, // 2: asr.v1.StreamingRecognizeResponse.results:type_name -> asr.v1.StreamingResult
	5, // 3: asr.v1.StreamingRecognizeResponse.error:type_name -> asr.v1.StreamError
	2, // 4: asr.v1.ASRService.StreamingRecognize:input_type -> asr.v1.StreamingRecognizeRequest
	3, // 5: asr.v1.ASRService.StreamingRecognize:output_type -> asr.v1.StreamingRecognizeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_asr_proto_init() }
func file_asr_proto_init() {
	if File_asr_proto != nil {
		return
	}
	file_asr_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamingRecognizeRequest_Config)(nil),
		(*StreamingRecognizeRequest_AudioContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asr_proto_rawDesc), len(file_asr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_proto_goTypes,
		DependencyIndexes: file_asr_proto_depIdxs,
		EnumInfos:         file_asr_proto_enumTypes,
		MessageInfos:      file_asr_proto_msgTypes,
	}.Build()
	File_asr_proto = out.File
	file_asr_proto_goTypes = nil
	file_asr_proto_depIdxs = nil
}
